server:
   port: 8080
   context-path: /movietheatre
   
spring:
   datasource:
      type: com.mchange.v2.c3p0.ComboPooledDataSource
      driverClassName: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/movietheatre?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Wanghao1994
      initialSize: 1
      minIdle: 1
      maxActive: 6
   jpa:
      database: MYSQL
      show-sql: false
      generate-ddl: true
      hibernate:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        ddl-auto: update
   mvc: # 对 jsp 支持，视图解析映射
     view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
#日志
log:
  path : d:/logs/movietheatre